const KEY='salon-performance-v4', OLD_KEY='salon-performance-v3';
const DESIGNERS=['PS62 QQ','PS8 Teddy','PS8 KJ','PS5 Mark','PS5 jolie','PS2 lori','PS2 kyra','PS2 小橘','PS2 polly','公主 ben','公主 萊恩','PS2 Allan','PS5 小P','PS8 Jenny','PS36 小樂','PS81 采連'];
const baseState={revenues:[],ads:[],subsidyReports:[],trafficSubsidyReports:[],settings:{margin:50,goals:{},designers:DESIGNERS,cloud:{url:'',anonKey:'',workspaceKey:'',autoSync:false}}};
const clone=o=>JSON.parse(JSON.stringify(o));
let loaded=JSON.parse(localStorage.getItem(KEY)||'null');
if(!loaded){const old=JSON.parse(localStorage.getItem(OLD_KEY)||'null');loaded=old?{...clone(baseState),...old,settings:{...clone(baseState).settings,...(old.settings||{}),goals:{},cloud:clone(baseState).settings.cloud}}:clone(baseState)}
const state=loaded; state.revenues ||= []; state.ads ||= []; state.subsidyReports ||= []; state.trafficSubsidyReports ||= []; state.settings ||= {}; state.settings.goals ||= {}; state.settings.designers ||= DESIGNERS; state.settings.cloud ||= clone(baseState).settings.cloud;
function recalcSavedSubsidyReports(){state.subsidyReports=state.subsidyReports.map(r=>{const actual=Number(r.actualAdFee)||((Number(r.monthlyAdFee)||0)*1.05),online=Number(r.onlineRevenue)||0,roas=actual?online/actual:0,roasHit=roas>=3.5;const socialPost=roasHit?'':r.socialPost,replyWithin=roasHit?'':r.replyWithin,followSop=roasHit?'':r.followSop;const hits=[socialPost,replyWithin,followSop].filter(v=>v==='yes').length,all3=!roasHit&&hits===3,pct=roasHit?50:(hits*10+(all3?10:0)),departmentSubsidy=actual*pct/100,designerBurden=Math.max(0,actual-departmentSubsidy);return{...r,actualAdFee:actual,roas,roasHit,socialPost,replyWithin,followSop,allThreeBonus:all3,subsidyPercent:pct,departmentSubsidy,designerBurden}});localStorage.setItem(KEY,JSON.stringify(state))}
recalcSavedSubsidyReports();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n)||0);
const pct=n=>`${(Number(n)||0).toFixed(1)}%`; const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const today=localDate(), monthNow=today.slice(0,7);
function save(){localStorage.setItem(KEY,JSON.stringify(state));if(state.settings.cloud?.autoSync) cloudPush(true).catch(()=>{})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function selectedMonth(){return $('#monthFilter').value||monthNow} function inMonth(date){return String(date).slice(0,7)===selectedMonth()}
function currentRevenues(){return state.revenues.filter(r=>inMonth(r.date))} function currentAds(){return state.ads.filter(a=>inMonth(a.date))}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatReplyMinutes(value){const mins=Math.max(0,Math.floor(Number(value)||0));if(!mins)return '';const h=Math.floor(mins/60),m=mins%60;if(h&&m)return `${h} 小時 ${m} 分鐘`;if(h)return `${h} 小時`;return `${m} 分鐘`}
function parseReplyMinutes(text){const raw=String(text||'').trim();if(!raw)return 0;if(/^\d+(?:\.\d+)?$/.test(raw))return Math.round(Number(raw));const h=raw.match(/(\d+(?:\.\d+)?)\s*(?:小時|時|h)/i);const m=raw.match(/(\d+(?:\.\d+)?)\s*(?:分鐘|分|min)/i);return Math.round((h?Number(h[1])*60:0)+(m?Number(m[1]):0))}
function updateReplyTimeDisplay(){const f=$('#subsidyForm');if(!f||!f.elements.replyMinutes)return;const raw=f.elements.replyMinutes.value;const hasValue=raw!==''&&raw!=null;const mins=hasValue?Math.max(0,Math.floor(Number(raw)||0)):0;const text=hasValue?formatReplyMinutes(mins):'';f.elements.replyTime.value=text;const out=$('#replyTimeFormatted');if(out){out.textContent=text||'尚未輸入時間';out.classList.toggle('empty',!text)}$$('#replyTimeQuick .time-quick-btn').forEach(b=>b.classList.toggle('selected',hasValue&&Number(b.dataset.minutes)===mins));$$('#replyMinuteTail .minute-tail-btn').forEach(b=>b.classList.toggle('selected',hasValue&&Number(b.dataset.digit)===mins%10))}
function setupDefaults(){ $('#monthFilter').value=monthNow; $$('input[type=date]').forEach(i=>i.value=today); const sm=$('#subsidyForm [name=month]'); if(sm) sm.value=monthNow; const tm=$('#trafficSubsidyForm [name=month]'); if(tm) tm.value=monthNow; fillDesignerSelect(); fillSettings(); fillCloud(); resetChoiceGroups(); updateSubsidyCalc(); updateReplyTimeDisplay(); updateTrafficSubsidyCalc() }
function fillSettings(){ $('#settingsForm [name=margin]').value=state.settings.margin??50; $('#settingsForm [name=goal]').value=state.settings.goals[selectedMonth()]??'' }
function fillCloud(){const c=state.settings.cloud; const f=$('#cloudForm'); f.elements.url.value=c.url||'';f.elements.anonKey.value=c.anonKey||'';f.elements.workspaceKey.value=c.workspaceKey||'';f.elements.autoSync.checked=!!c.autoSync; updateCloudStatus()}
function switchView(view){const titles={subsidy:'廣告補助回報','traffic-subsidy':'流量型補助','subsidy-records':'補助回報紀錄',records:'紀錄',reports:'報表',cloud:'雲端同步',settings:'設定'};$$('.view').forEach(v=>v.classList.remove('active'));const target=$(`#${view}View`);if(!target)return;target.classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageTitle').textContent=titles[view];if(view==='settings')fillSettings();if(view==='cloud')fillCloud();if(view==='reports')renderReports()}
function render(){if($('#dashboardView'))renderDashboard();renderTables();renderSubsidyTable();renderTrafficSubsidyTable();renderReports();fillSettings()}
function renderDashboard(){const rows=currentRevenues(),ads=currentAds();const total=rows.reduce((s,r)=>s+Number(r.amount),0),count=rows.length,adRev=rows.filter(r=>r.adAttributed==='yes').reduce((s,r)=>s+Number(r.amount),0),spend=ads.reduce((s,a)=>s+Number(a.amount),0),roas=spend?adRev/spend:null,margin=(Number(state.settings.margin)||0)/100,roi=spend?((adRev*margin-spend)/spend)*100:null,newCount=rows.filter(r=>r.customerType==='新客').length;$('#totalRevenue').textContent=money(total);$('#totalCustomers').textContent=count;$('#avgTicket').textContent=money(count?total/count:0);$('#adSpend').textContent=money(spend);$('#adRevenue').textContent=money(adRev);$('#roas').textContent=roas===null?'—':`${roas.toFixed(2)}x`;$('#roi').textContent=roi===null?'—':pct(roi);$('#newCustomerRate').textContent=pct(count?newCount/count*100:0);$('#revenuePeriodLabel').textContent=selectedMonth().replace('-',' / ');renderGoal(total);renderSource(rows);drawRevenueChart(rows)}
function renderGoal(total){const goal=Number(state.settings.goals[selectedMonth()]||0),rate=goal?total/goal*100:0;$('#goalAmount').textContent=goal?money(goal):'尚未設定';$('#goalRate').textContent=goal?pct(rate):'0%';$('#goalBar').style.width=`${Math.min(100,rate)}%`;$('#goalMeta').textContent=goal?`目前 ${money(total)}，還差 ${money(Math.max(0,goal-total))}`:'到設定頁輸入本月目標'}
function renderSource(rows){const el=$('#sourceBreakdown'),sums={};rows.forEach(r=>sums[r.source]=(sums[r.source]||0)+Number(r.amount));const entries=Object.entries(sums).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>x[1]));el.innerHTML=entries.length?entries.map(([n,v])=>`<div class="source-row"><span>${escapeHtml(n)}</span><strong>${money(v)}</strong><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join(''):'<div class="help">這個月份還沒有業績資料。</div>'}
function drawRevenueChart(rows){const canvas=$('#revenueChart');if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*2,h=canvas.height=520;ctx.clearRect(0,0,w,h);const daily={};rows.forEach(r=>daily[r.date]=(daily[r.date]||0)+Number(r.amount));const entries=Object.entries(daily).sort((a,b)=>a[0].localeCompare(b[0]));ctx.scale(2,2);const W=w/2,H=h/2,pad={l:46,r:18,t:18,b:34};ctx.strokeStyle='#e5e5e0';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=pad.t+(H-pad.t-pad.b)*i/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(W-pad.r,y);ctx.stroke()}if(!entries.length){ctx.fillStyle='#888';ctx.font='14px sans-serif';ctx.fillText('尚無資料',pad.l,H/2);ctx.setTransform(1,0,0,1,0,0);return}const max=Math.max(...entries.map(x=>x[1]),1);ctx.strokeStyle='#7c5cff';ctx.lineWidth=3;ctx.lineJoin='round';ctx.beginPath();entries.forEach(([d,v],i)=>{const x=pad.l+(W-pad.l-pad.r)*(entries.length===1?.5:i/(entries.length-1)),y=H-pad.b-(H-pad.t-pad.b)*(v/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#6d6d6d';ctx.font='11px sans-serif';entries.forEach(([d],i)=>{const x=pad.l+(W-pad.l-pad.r)*(entries.length===1?.5:i/(entries.length-1));if(entries.length<=10||i%Math.ceil(entries.length/8)===0)ctx.fillText(d.slice(8),x-6,H-12)});ctx.setTransform(1,0,0,1,0,0)}

function fillDesignerSelect(){for(const sel of [$('#subsidyDesigner'),$('#trafficSubsidyDesigner')].filter(Boolean)){const current=sel.value;sel.innerHTML='<option value="">請選擇設計師</option>'+state.settings.designers.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join('');if(state.settings.designers.includes(current))sel.value=current}}
function resetChoiceGroups(){const f=$('#subsidyForm');if(!f)return;f.querySelectorAll('.choice-btn').forEach(b=>b.classList.remove('selected'));const talent=f.querySelector('[data-choice="talentType"] .choice-btn[data-value="一般"]');if(talent)talent.classList.add('selected');f.elements.talentType.value='一般'}
function setChoice(groupName,value){const group=$(`#subsidyForm [data-choice="${groupName}"]`);if(!group)return;group.querySelectorAll('.choice-btn').forEach(b=>b.classList.toggle('selected',b.dataset.value===value));const hidden=$(`#subsidyForm [name="${groupName}"]`);if(hidden)hidden.value=value;updateSubsidyCalc()}
function subsidyCalcValues(){const f=$('#subsidyForm');if(!f)return{actual:0,online:0,roas:0,pct:0,subsidy:0,burden:0,all3:false};const monthly=Number(f.elements.monthlyAdFee.value)||0,actual=monthly*1.05,online=Number(f.elements.onlineRevenue.value)||0,roas=actual?online/actual:0;const criteria=['socialPost','replyWithin','followSop'].map(k=>f.elements[k].value==='yes');const hits=criteria.filter(Boolean).length,all3=hits===3,roasHit=roas>=3.5,pct=roasHit?50:(hits*10+(all3?10:0)),subsidy=actual*pct/100,burden=Math.max(0,actual-subsidy);return{monthly,actual,online,roas,pct,subsidy,burden,all3,roasHit}}
function setCriteriaLocked(locked){const f=$('#subsidyForm');if(!f)return;['socialPost','replyWithin','followSop'].forEach(name=>{const input=f.elements[name],group=f.querySelector(`[data-choice="${name}"]`),card=group?.closest('.criteria-card');if(locked){input.value='';group?.querySelectorAll('.choice-btn').forEach(b=>{b.classList.remove('selected');b.disabled=true});card?.classList.add('locked')}else{group?.querySelectorAll('.choice-btn').forEach(b=>b.disabled=false);card?.classList.remove('locked')}})}
function updateSubsidyCalc(){const f=$('#subsidyForm');if(!f)return;let v=subsidyCalcValues();setCriteriaLocked(v.roasHit);if(v.roasHit)v=subsidyCalcValues();f.elements.actualAdFee.value=v.actual?money(v.actual):'';f.elements.reportRoas.value=v.actual?`${v.roas.toFixed(2)}x`:'';const badge=$('#roasTargetBadge');if(v.actual){badge.textContent=v.roasHit?'✓ 已達 3.5 倍｜固定補助 50%｜配合度免填':'✕ 未達 3.5 倍｜請填寫下方配合度';badge.className=`auto-badge ${v.roasHit?'ok':'bad'}`}else{badge.textContent='輸入廣告費與網路業績後自動判斷';badge.className='auto-badge neutral'}$('#allThreeBonus').textContent=v.roasHit?'不適用':(v.all3?'10%':'0%');$('#subsidyPercent').textContent=`${v.pct}%`;$('#departmentSubsidy').textContent=money(v.subsidy);$('#designerBurden').textContent=money(v.burden)}
function currentSubsidyReports(){return state.subsidyReports.filter(r=>r.month===selectedMonth())}
function renderSubsidyTable(){const el=$('#subsidyTable');if(!el)return;const rows=currentSubsidyReports().slice().sort((a,b)=>a.designer.localeCompare(b.designer,'zh-Hant'));$('#subsidyRecordCount').textContent=`${rows.length} 筆`;el.innerHTML=rows.length?rows.map(r=>`<tr><td>${r.month}</td><td>${escapeHtml(r.designer)}</td><td>${escapeHtml(r.adItem||'—')}</td><td>${money(r.monthlyAdFee)}</td><td>${money(r.actualAdFee)}</td><td>${money(r.onlineRevenue)}</td><td>${Number(r.roas||0).toFixed(2)}x</td><td>${r.roasHit?'✓':'✕'}</td><td>${r.roasHit?'—':(r.socialPost==='yes'?'✓':'✕')}</td><td>${r.roasHit?'—':(r.replyWithin==='yes'?'✓':'✕')}</td><td>${escapeHtml(r.replyTime||'—')}</td><td>${r.roasHit?'—':(r.followSop==='yes'?'✓':'✕')}</td><td>${r.roasHit?'—':(r.allThreeBonus?'10%':'0%')}</td><td>${r.subsidyPercent}%</td><td>${money(r.departmentSubsidy)}</td><td>${money(r.designerBurden)}</td><td>${escapeHtml(r.talentType||'一般')}</td><td><div class="row-actions"><button class="edit-subsidy-btn" data-id="${r.id}">編輯</button><button class="delete-btn" data-type="subsidy" data-id="${r.id}">刪除</button></div></td></tr>`).join(''):'<tr><td colspan="18">這個月份尚無補助回報紀錄</td></tr>'}
let subsidyEditId=null;function resetSubsidyForm(){const f=$('#subsidyForm');if(!f)return;subsidyEditId=null;f.reset();f.elements.month.value=selectedMonth();resetChoiceGroups();updateSubsidyCalc();updateReplyTimeDisplay()}
function trafficSubsidyCalcValues(){const f=$('#trafficSubsidyForm');if(!f)return{monthly:0,actual:0,revenue:0,pct:0,subsidy:0,burden:0};const monthly=Number(f.elements.monthlyAdFee.value)||0,actual=monthly*1.05,revenue=Number(f.elements.actualRevenue.value)||0;let pct=0;if(revenue>=300000)pct=50;else if(revenue>=250000)pct=40;else if(revenue>=200000)pct=30;else if(revenue>=150000)pct=20;const subsidy=actual*pct/100,burden=Math.max(0,actual-subsidy);return{monthly,actual,revenue,pct,subsidy,burden}}
function updateTrafficSubsidyCalc(){const f=$('#trafficSubsidyForm');if(!f)return;const v=trafficSubsidyCalcValues();f.elements.actualAdFee.value=money(v.actual);$('#trafficSubsidyPercent').textContent=`${v.pct}%`;$('#trafficDepartmentSubsidy').textContent=money(v.subsidy);$('#trafficDesignerBurden').textContent=money(v.burden);const badge=$('#trafficTierBadge');if(!badge)return;if(!v.revenue){badge.textContent='輸入實業績後自動判斷';badge.className='auto-badge neutral'}else if(v.pct){badge.textContent=`達成 ${money(v.revenue)}｜補助 ${v.pct}%`;badge.className='auto-badge hit'}else{badge.textContent=`目前 ${money(v.revenue)}｜未達 15 萬門檻`;badge.className='auto-badge miss'}}
function resetTrafficSubsidyForm(){const f=$('#trafficSubsidyForm');if(!f)return;f.reset();f.elements.month.value=selectedMonth();fillDesignerSelect();updateTrafficSubsidyCalc()}
function currentTrafficSubsidyReports(){return state.trafficSubsidyReports.filter(r=>r.month===selectedMonth())}
function renderTrafficSubsidyTable(){const el=$('#trafficSubsidyTable');if(!el)return;const rows=currentTrafficSubsidyReports().slice().sort((a,b)=>a.designer.localeCompare(b.designer,'zh-Hant'));$('#trafficSubsidyRecordCount').textContent=`${rows.length} 筆`;el.innerHTML=rows.length?rows.map(r=>`<tr><td>${r.month}</td><td>${escapeHtml(r.designer)}</td><td>${money(r.monthlyAdFee)}</td><td>${money(r.actualAdFee)}</td><td>${money(r.actualRevenue)}</td><td>${r.subsidyPercent}%</td><td>${money(r.departmentSubsidy)}</td><td>${money(r.designerBurden)}</td><td><div class="row-actions"><button class="delete-btn" data-type="traffic-subsidy" data-id="${r.id}">刪除</button></div></td></tr>`).join(''):'<tr><td colspan="9">這個月份尚無流量型補助紀錄</td></tr>'}
function renderTables(){const rows=currentRevenues().sort((a,b)=>b.date.localeCompare(a.date));$('#recordCount').textContent=`${rows.length} 筆`;$('#revenueTable').innerHTML=rows.length?rows.map(r=>`<tr><td>${r.date}</td><td>${money(r.amount)}</td><td>${escapeHtml(r.service||'—')}</td><td>${escapeHtml(r.customerType)}</td><td>${escapeHtml(r.source)}</td><td>${r.adAttributed==='yes'?'是':'否'}</td><td>${escapeHtml(r.designer||'—')}</td><td><div class="row-actions"><button class="edit-btn" data-type="revenue" data-id="${r.id}">編輯</button><button class="delete-btn" data-type="revenue" data-id="${r.id}">刪除</button></div></td></tr>`).join(''):'<tr><td colspan="8">尚無資料</td></tr>';const ads=currentAds().sort((a,b)=>b.date.localeCompare(a.date));$('#adRecordCount').textContent=`${ads.length} 筆`;$('#adTable').innerHTML=ads.length?ads.map(a=>`<tr><td>${a.date}</td><td>${escapeHtml(a.platform)}</td><td>${money(a.amount)}</td><td>${escapeHtml(a.campaign||'—')}</td><td><div class="row-actions"><button class="edit-btn" data-type="ad" data-id="${a.id}">編輯</button><button class="delete-btn" data-type="ad" data-id="${a.id}">刪除</button></div></td></tr>`).join(''):'<tr><td colspan="5">尚無資料</td></tr>'}
function dailyReport(){const map={};currentRevenues().forEach(r=>{const x=map[r.date]||={date:r.date,revenue:0,count:0,adRevenue:0,newCount:0};x.revenue+=Number(r.amount);x.count++;if(r.adAttributed==='yes')x.adRevenue+=Number(r.amount);if(r.customerType==='新客')x.newCount++});return Object.values(map).sort((a,b)=>a.date.localeCompare(b.date))}
function monthlyReport(){const months=[...new Set([...state.revenues.map(r=>r.date.slice(0,7)),...state.ads.map(a=>a.date.slice(0,7)),...Object.keys(state.settings.goals)])].sort().reverse();return months.map(m=>{const rs=state.revenues.filter(r=>r.date.slice(0,7)===m),as=state.ads.filter(a=>a.date.slice(0,7)===m),revenue=rs.reduce((s,r)=>s+Number(r.amount),0),count=rs.length,spend=as.reduce((s,a)=>s+Number(a.amount),0),adRevenue=rs.filter(r=>r.adAttributed==='yes').reduce((s,r)=>s+Number(r.amount),0),goal=Number(state.settings.goals[m]||0);return{month:m,revenue,count,avg:count?revenue/count:0,spend,adRevenue,roas:spend?adRevenue/spend:null,goalRate:goal?revenue/goal*100:null}})}
function renderReports(){const ds=dailyReport();$('#dailyReportTable').innerHTML=ds.length?ds.map(x=>`<tr><td>${x.date}</td><td>${money(x.revenue)}</td><td>${x.count}</td><td>${money(x.revenue/x.count)}</td><td>${money(x.adRevenue)}</td><td>${x.newCount}</td><td>${x.count-x.newCount}</td></tr>`).join(''):'<tr><td colspan="7">尚無資料</td></tr>';const ms=monthlyReport();$('#monthlyReportTable').innerHTML=ms.length?ms.map(x=>`<tr><td>${x.month}</td><td>${money(x.revenue)}</td><td>${x.count}</td><td>${money(x.avg)}</td><td>${money(x.spend)}</td><td>${money(x.adRevenue)}</td><td>${x.roas===null?'—':x.roas.toFixed(2)+'x'}</td><td>${x.goalRate===null?'—':pct(x.goalRate)}</td></tr>`).join(''):'<tr><td colspan="8">尚無資料</td></tr>'}
function options(arr,val){return arr.map(x=>`<option${x===val?' selected':''}>${escapeHtml(x)}</option>`).join('')}
let editCtx=null;function openEdit(type,id){const item=(type==='revenue'?state.revenues:state.ads).find(x=>x.id===id);if(!item)return;editCtx={type,id};$('#editTitle').textContent=type==='revenue'?'編輯業績':'編輯廣告費';$('#editFields').innerHTML=type==='revenue'?`<label>日期<input type="date" name="date" value="${item.date}" required></label><label>金額<input type="number" name="amount" min="0" value="${item.amount}" required></label><label>服務項目<input name="service" value="${escapeHtml(item.service||'')}"></label><label>客人類型<select name="customerType">${options(['新客','回客','介紹'],item.customerType)}</select></label><label>客源<select name="source">${options(['Meta','Instagram','LINE','Google','介紹','自然客','其他'],item.source)}</select></label><label>是否來自廣告<select name="adAttributed"><option value="yes"${item.adAttributed==='yes'?' selected':''}>是</option><option value="no"${item.adAttributed==='no'?' selected':''}>否</option></select></label><label>設計師<input name="designer" value="${escapeHtml(item.designer||'')}"></label><label class="span-2">備註<textarea name="note" rows="3">${escapeHtml(item.note||'')}</textarea></label>`:`<label>日期<input type="date" name="date" value="${item.date}" required></label><label>平台<select name="platform">${options(['Meta','Google','TikTok','其他'],item.platform)}</select></label><label>廣告費<input type="number" name="amount" min="0" value="${item.amount}" required></label><label>活動名稱<input name="campaign" value="${escapeHtml(item.campaign||'')}"></label><label class="span-2">備註<textarea name="note" rows="3">${escapeHtml(item.note||'')}</textarea></label>`;$('#editDialog').showModal()}
function csvDownload(filename,headers,rows){const esc=v=>`"${String(v??'').replaceAll('"','""')}"`,csv='\ufeff'+[headers,...rows].map(r=>r.map(esc).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function cloudConfigured(){const c=state.settings.cloud;return !!(c.url&&c.anonKey&&c.workspaceKey)} function updateCloudStatus(text,mode){const el=$('#cloudStatus');if(!el)return;if(text){el.textContent=text;el.className=`status-pill ${mode||''}`;return}el.textContent=cloudConfigured()?'已設定':'尚未設定';el.className=`status-pill ${cloudConfigured()?'ok':''}`}
async function cloudRequest(method,body){const c=state.settings.cloud,url=c.url.replace(/\/$/,'')+`/rest/v1/salon_app_state${method==='GET'?`?workspace_key=eq.${encodeURIComponent(c.workspaceKey)}&select=payload,updated_at`: '?on_conflict=workspace_key'}`;const headers={'apikey':c.anonKey,'Authorization':`Bearer ${c.anonKey}`,'Content-Type':'application/json','X-Workspace-Key':c.workspaceKey};if(method==='POST')headers['Prefer']='resolution=merge-duplicates,return=minimal';const res=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});if(!res.ok)throw new Error(`${res.status} ${await res.text()}`);return method==='GET'?res.json():null}
async function cloudPush(silent=false){if(!cloudConfigured()){if(!silent)toast('請先完成雲端設定');return}try{updateCloudStatus('上傳中…');const payload={revenues:state.revenues,ads:state.ads,subsidyReports:state.subsidyReports,trafficSubsidyReports:state.trafficSubsidyReports,settings:{margin:state.settings.margin,goals:state.settings.goals,designers:state.settings.designers}};await cloudRequest('POST',{workspace_key:state.settings.cloud.workspaceKey,payload,updated_at:new Date().toISOString()});updateCloudStatus('已同步','ok');if(!silent)toast('已上傳到雲端')}catch(e){console.error(e);updateCloudStatus('同步失敗','bad');if(!silent)toast('雲端上傳失敗，請檢查設定')}}
async function cloudPull(){if(!cloudConfigured()){toast('請先完成雲端設定');return}try{updateCloudStatus('下載中…');const rows=await cloudRequest('GET');if(!rows.length){updateCloudStatus('雲端尚無資料','bad');toast('雲端尚無資料');return}const p=rows[0].payload||{};if(!confirm('從雲端下載會覆蓋目前這台裝置的業績與廣告資料，確定繼續？')){updateCloudStatus('已設定','ok');return}state.revenues=Array.isArray(p.revenues)?p.revenues:[];state.ads=Array.isArray(p.ads)?p.ads:[];state.subsidyReports=Array.isArray(p.subsidyReports)?p.subsidyReports:[];state.trafficSubsidyReports=Array.isArray(p.trafficSubsidyReports)?p.trafficSubsidyReports:[];state.settings.designers=Array.isArray(p.settings?.designers)&&p.settings.designers.length?p.settings.designers:state.settings.designers;state.settings.margin=p.settings?.margin??state.settings.margin;state.settings.goals=p.settings?.goals||{};localStorage.setItem(KEY,JSON.stringify(state));render();updateCloudStatus('已同步','ok');toast('已從雲端下載')}catch(e){console.error(e);updateCloudStatus('同步失敗','bad');toast('雲端下載失敗，請檢查設定')}}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#monthFilter').addEventListener('change',()=>{render();fillSettings()});
if($('#adForm'))$('#adForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.ads.push({id:uid(),date:f.get('date'),platform:f.get('platform'),amount:Number(f.get('amount')),campaign:f.get('campaign'),note:f.get('note')});save();e.currentTarget.reset();e.currentTarget.querySelector('[name=date]').value=today;toast('廣告費已儲存');render();switchView('subsidy')});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.settings.margin=Number(f.get('margin'));const g=Number(f.get('goal'));if(g>0)state.settings.goals[selectedMonth()]=g;else delete state.settings.goals[selectedMonth()];save();toast('設定已儲存');render();switchView('subsidy')});
$('#clearData').addEventListener('click',()=>{if(confirm('確定要清除全部業績與廣告資料嗎？目標與雲端設定會保留。')){state.revenues=[];state.ads=[];save();render();toast('資料已清除')}});
document.addEventListener('click',e=>{const eb=e.target.closest('.edit-btn');if(eb){openEdit(eb.dataset.type,eb.dataset.id);return}const db=e.target.closest('.delete-btn');if(!db)return;if(!confirm('確定刪除這筆紀錄？'))return;if(db.dataset.type==='revenue')state.revenues=state.revenues.filter(x=>x.id!==db.dataset.id);else if(db.dataset.type==='ad')state.ads=state.ads.filter(x=>x.id!==db.dataset.id);else if(db.dataset.type==='subsidy')state.subsidyReports=state.subsidyReports.filter(x=>x.id!==db.dataset.id);else if(db.dataset.type==='traffic-subsidy')state.trafficSubsidyReports=state.trafficSubsidyReports.filter(x=>x.id!==db.dataset.id);save();render();toast('紀錄已刪除')});
$('#editForm').addEventListener('submit',e=>{e.preventDefault();if(!editCtx)return;const f=new FormData(e.currentTarget),arr=editCtx.type==='revenue'?state.revenues:state.ads,i=arr.findIndex(x=>x.id===editCtx.id);if(i<0)return;if(editCtx.type==='revenue')arr[i]={...arr[i],date:f.get('date'),amount:Number(f.get('amount')),service:f.get('service'),customerType:f.get('customerType'),source:f.get('source'),adAttributed:f.get('adAttributed'),designer:f.get('designer'),note:f.get('note')};else arr[i]={...arr[i],date:f.get('date'),platform:f.get('platform'),amount:Number(f.get('amount')),campaign:f.get('campaign'),note:f.get('note')};save();$('#editDialog').close();render();toast('紀錄已更新')});
function closeEdit(){editCtx=null;$('#editDialog').close()} $('#closeEdit').addEventListener('click',closeEdit);$('#cancelEdit').addEventListener('click',closeEdit);

$('#subsidyForm').addEventListener('click',e=>{const b=e.target.closest('.choice-btn');if(!b||b.disabled)return;const g=b.closest('[data-choice]');if(!g)return;setChoice(g.dataset.choice,b.dataset.value)});
$('#subsidyForm [name=monthlyAdFee]').addEventListener('input',updateSubsidyCalc);$('#subsidyForm [name=onlineRevenue]').addEventListener('input',updateSubsidyCalc);
$('#subsidyForm [name=replyMinutes]').addEventListener('input',updateReplyTimeDisplay);$('#replyTimeQuick').addEventListener('click',e=>{const b=e.target.closest('.time-quick-btn');if(!b)return;const input=$('#subsidyForm [name=replyMinutes]');input.value=b.dataset.minutes;updateReplyTimeDisplay();input.focus()});$('#replyMinuteTail').addEventListener('click',e=>{const b=e.target.closest('.minute-tail-btn');if(!b)return;const input=$('#subsidyForm [name=replyMinutes]');const digit=Number(b.dataset.digit);const current=input.value===''?0:Math.max(0,Math.floor(Number(input.value)||0));input.value=Math.floor(current/10)*10+digit;updateReplyTimeDisplay();input.focus()});
$('#subsidyForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f);if(!fd.get('designer')){toast('請先選擇設計師');return}if(!fd.get('adItem')){toast('請選擇廣告項目');return}const v=subsidyCalcValues();if(!v.roasHit){for(const k of ['socialPost','replyWithin','followSop'])if(!fd.get(k)){toast('未達 3.5 倍時，三項配合度都需要選擇達標或未達標');return}}const item={id:subsidyEditId||uid(),month:fd.get('month'),designer:fd.get('designer'),adItem:fd.get('adItem'),monthlyAdFee:Number(fd.get('monthlyAdFee'))||0,actualAdFee:v.actual,onlineRevenue:Number(fd.get('onlineRevenue'))||0,roas:v.roas,roasHit:v.roasHit,socialPost:fd.get('socialPost'),replyWithin:fd.get('replyWithin'),replyMinutes:Number(fd.get('replyMinutes'))||0,replyTime:fd.get('replyTime'),followSop:fd.get('followSop'),allThreeBonus:v.all3,subsidyPercent:v.pct,departmentSubsidy:v.subsidy,designerBurden:v.burden,talentType:fd.get('talentType')||'一般',createdAt:new Date().toISOString()};if(subsidyEditId){const i=state.subsidyReports.findIndex(x=>x.id===subsidyEditId);if(i>=0)state.subsidyReports[i]={...state.subsidyReports[i],...item}}else state.subsidyReports.push(item);save();const wasEdit=!!subsidyEditId;resetSubsidyForm();render();toast(wasEdit?'補助回報已更新':'補助回報已儲存');switchView('subsidy-records')});
$('#resetSubsidyForm').addEventListener('click',resetSubsidyForm);
$('#exportSubsidy').addEventListener('click',()=>{const rows=currentSubsidyReports();csvDownload(`廣告補助回報-${selectedMonth()}.csv`,['月份','姓名','廣告項目','每月廣告費用','實際廣告費用＋5%','網路業績','投報率','3.5倍達標','貼文及限時動態','1.5小時內回覆','回覆時間','遵循SOP','三項達標加10%','本次補助％數','事業部補助費用','設計師負擔金額','新秀／首次投放'],rows.map(r=>[r.month,r.designer,r.adItem,r.monthlyAdFee,r.actualAdFee,r.onlineRevenue,Number(r.roas||0).toFixed(2),r.roasHit?'達標':'未達標',r.roasHit?'不適用':(r.socialPost==='yes'?'達標':'未達標'),r.roasHit?'不適用':(r.replyWithin==='yes'?'達標':'未達標'),r.replyTime||'',r.roasHit?'不適用':(r.followSop==='yes'?'達標':'未達標'),r.roasHit?'不適用':(r.allThreeBonus?'10%':'0%'),`${r.subsidyPercent}%`,r.departmentSubsidy,r.designerBurden,r.talentType||'一般']))});
document.addEventListener('click',e=>{const b=e.target.closest('.edit-subsidy-btn');if(!b)return;const r=state.subsidyReports.find(x=>x.id===b.dataset.id);if(!r)return;subsidyEditId=r.id;switchView('subsidy');const f=$('#subsidyForm');f.elements.month.value=r.month;f.elements.designer.value=r.designer;f.elements.monthlyAdFee.value=r.monthlyAdFee;f.elements.onlineRevenue.value=r.onlineRevenue;f.elements.replyMinutes.value=Number(r.replyMinutes)||parseReplyMinutes(r.replyTime);updateReplyTimeDisplay();setChoice('adItem',r.adItem);setChoice('socialPost',r.socialPost);setChoice('replyWithin',r.replyWithin);setChoice('followSop',r.followSop);setChoice('talentType',r.talentType||'一般');updateSubsidyCalc();toast('已載入表單，修改後按儲存即可')});
$$('.report-tab').forEach(b=>b.addEventListener('click',()=>{$$('.report-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.report-panel').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.report}ReportPanel`).classList.add('active')}));
$('#exportDaily').addEventListener('click',()=>{const rows=dailyReport();csvDownload(`每日報表-${selectedMonth()}.csv`,['日期','業績','人數','平均客單','廣告客業績','新客','回客/其他'],rows.map(x=>[x.date,x.revenue,x.count,Math.round(x.revenue/x.count),x.adRevenue,x.newCount,x.count-x.newCount]))});
$('#exportMonthly').addEventListener('click',()=>{const rows=monthlyReport();csvDownload('每月報表.csv',['月份','總業績','人數','平均客單','廣告費','廣告業績','ROAS','目標達成率'],rows.map(x=>[x.month,x.revenue,x.count,Math.round(x.avg),x.spend,x.adRevenue,x.roas?.toFixed(2)||'',x.goalRate?.toFixed(1)||'']))});
const trafficForm=$('#trafficSubsidyForm');if(trafficForm){trafficForm.elements.monthlyAdFee.addEventListener('input',updateTrafficSubsidyCalc);trafficForm.elements.actualRevenue.addEventListener('input',updateTrafficSubsidyCalc);trafficForm.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(!fd.get('designer')){toast('請先選擇設計師');return}const v=trafficSubsidyCalcValues();const item={id:uid(),month:fd.get('month'),designer:fd.get('designer'),monthlyAdFee:Number(fd.get('monthlyAdFee'))||0,actualAdFee:v.actual,actualRevenue:Number(fd.get('actualRevenue'))||0,subsidyPercent:v.pct,departmentSubsidy:v.subsidy,designerBurden:v.burden,createdAt:new Date().toISOString()};state.trafficSubsidyReports.push(item);save();resetTrafficSubsidyForm();render();toast('流量型補助已儲存')});$('#resetTrafficSubsidyForm').addEventListener('click',resetTrafficSubsidyForm)}
$('#cloudForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.settings.cloud={url:String(f.get('url')||'').trim(),anonKey:String(f.get('anonKey')||'').trim(),workspaceKey:String(f.get('workspaceKey')||'').trim(),autoSync:f.get('autoSync')==='on'};localStorage.setItem(KEY,JSON.stringify(state));updateCloudStatus();toast('雲端設定已儲存')});
$('#generateWorkspace').addEventListener('click',()=>{$('#cloudForm [name=workspaceKey]').value=uid();toast('已產生 Workspace Key，記得儲存設定')});$('#cloudUpload').addEventListener('click',()=>cloudPush(false));$('#cloudDownload').addEventListener('click',cloudPull);
window.addEventListener('resize',()=>{if($('#revenueChart'))drawRevenueChart(currentRevenues())});setupDefaults();render();switchView('subsidy');if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('service-worker.js').catch(()=>{});
